.github/workflows/spell.yml
README.md
dev/cspell/cspell.config.yaml

CSpell Actionを追加

---

frontend/octavio/__test__/pages/scoring/[code].test.tsx
frontend/octavio/__test__/pages/users.test.tsx
frontend/octavio/types/User.ts
frontend/octavio/yarn.lock

* add: ユーザー一覧ページの単体テストを追加
* update: 単体テスト実行時に警告が発生するので yarn.lock を更新
* delete: screen.debug を削除

add: ユーザー一覧ページの単体テストを追加 / update: 単体テスト実行時に警告が発生するので yarn.lock を更新

---

frontend/octavio/__test__/pages/index.test.tsx

add: Home ページの単体テストを追加

---

frontend/octavio/.gitignore
frontend/octavio/__e2e__/pages/signUp.ts
frontend/octavio/__e2e__/signUp.test.ts
frontend/octavio/components/MarkdownPreview.tsx
frontend/octavio/hooks/auth.ts
frontend/octavio/pages/signUp.tsx

add: 参加者登録ページの e2e テストを追加

---

frontend/octavio/__e2e__/navbar.test.ts
frontend/octavio/__e2e__/pages/login.ts
frontend/octavio/__e2e__/pages/ranking.ts
frontend/octavio/__e2e__/ranking.test.ts

* add: ranking ページの e2e テストを追加

add: ranking ページの e2e テストを追加

---

frontend/octavio/__e2e__/pages/scoring/[code].ts
frontend/octavio/__e2e__/scoring/[code].test.ts
frontend/octavio/components/ScoringAnswerForm.tsx
frontend/octavio/pages/scoring/[code].tsx

add: 採点ページの e2e テストを追加

---

frontend/octavio/__e2e__/notices.test.ts
frontend/octavio/__e2e__/pages/notice.ts

add: 通知一覧ページの e2e テストを追加

---

frontend/octavio/__e2e__/pages/profile.ts
frontend/octavio/__e2e__/profile.test.ts
frontend/octavio/pages/profile.tsx

add: プロフィールページの e2e テストを追加

---

frontend/octavio/__e2e__/pages/users.ts
frontend/octavio/__e2e__/users.test.ts

add: ユーザー一覧ページの e2e テストを追加

---

frontend/octavio/__e2e__/pages/teamInfo.ts
frontend/octavio/__e2e__/team_info.test.ts
frontend/octavio/components/HiddenInput.tsx
frontend/octavio/pages/team_info.tsx

add: チーム情報ページの e2e テストを追加

---

dev/cspell/cspell.config.yaml
dev/cspell/dictionary.txt
frontend/octavio/.eslintrc.json
frontend/octavio/.gitignore
frontend/octavio/.storybook/main.ts
frontend/octavio/.storybook/preview.ts
frontend/octavio/README.md
frontend/octavio/components/NavBar.stories.ts
frontend/octavio/components/_const.ts
frontend/octavio/hooks/api.ts
frontend/octavio/package.json
frontend/octavio/pnpm-lock.yaml
frontend/octavio/public/mockServiceWorker.js
frontend/octavio/tailwind.config.js

add: storybook を追加

---

frontend/octavio/components/ConditionalText.tsx
frontend/octavio/components/HiddenInput.tsx
frontend/octavio/components/MarkdownPreview.tsx

* fix: react/require-default-props の警告が出ていた問題を修正

fix: react/require-default-props の警告が出ていた問題を修正

---

dev/cspell/dictionary.txt
frontend/octavio/app/login/page.tsx
frontend/octavio/app/problems/[problemId]/page.tsx
frontend/octavio/app/signUp/page.tsx
frontend/octavio/components/Alerts.tsx
frontend/octavio/components/AnswerForm.tsx
frontend/octavio/components/AnswerListSection.tsx
frontend/octavio/components/Card.tsx
frontend/octavio/components/ConditionalText.tsx
frontend/octavio/components/HiddenInput.tsx
frontend/octavio/components/HoverCopyText.tsx
frontend/octavio/components/MarkdownPreview.tsx
frontend/octavio/components/ProblemCard.tsx
frontend/octavio/package.json
frontend/octavio/pnpm-lock.yaml

* add: CSS を動的に変更している部分を clsx を追加して置き換え

add: CSS を動的に変更している部分を clsx を追加して置き換え

---

frontend/octavio/__test__/pages/index.test.tsx
frontend/octavio/__test__/pages/problems/[problemId].test.tsx
frontend/octavio/__test__/pages/problems/index.test.tsx
frontend/octavio/__test__/pages/scoring/[code].test.tsx
frontend/octavio/__test__/pages/scoring/index.test.tsx

* update: MarkdownPreview を mock するように改善

単体テストのリファクタリング

---

frontend/octavio/app/login/page.tsx
frontend/octavio/components/alerts.tsx

fix: ログインページのローディング中がうまく動作していない問題を修正

---

frontend/octavio/app/signUp/page.tsx

fix: 登録ページのローディング中がうまく動作していない問題を修正

---

frontend/octavio/app/problems/[problemId]/page.tsx

fix: 再展開時の animate-load がうまく動作していない問題を修正

---

frontend/octavio/app/problems/[problemId]/_components/multiple-answer-form.tsx

fix: 選択式問題の回答送信したときに自分自身が送信したのに、メッセージが表示されるのを修正

---

frontend/duardo/app/problems/new/descriptive/page.test.tsx

add: new problem test

---

frontend/packages/contestant/.storybook/main.js
frontend/packages/contestant/app/components/app-shell/header.tsx
frontend/packages/contestant/app/routes.gen.ts
frontend/packages/contestant/package.json
frontend/pnpm-lock.yaml

使っていない chromatic が紛れこんで storybook を破壊していたので外したりもしている

Link の型エラーを修正

---

.github/workflows/frontend-ci.yml

FYI: https://github.com/ictsc/ictsc-regalia/settings/branch_protection_rules/39113621
これでいいのかレビューしてほしい

フロントエンド側の Lint も branch protection の対象にする

---

.github/actions/setup-go/action.yaml
.github/workflows/backend-ci.yml

Go Module のキャッシュをデフォルトブランチだけでやるような作業をまとめる

feat: introduce setup-go

---

.github/actions/setup-go/action.yaml
backend/Dockerfile

Go の互換性を信じて go.mod の toolchain に頼ることにする

feat: use go toolchain

---

backend/cmd/scoreserver/config.go
backend/cmd/scoreserver/option.go
backend/go.mod
backend/go.sum
backend/scoreserver/admin/auth/authn_test.go
backend/scoreserver/admin/auth/authz.go
backend/scoreserver/admin/auth/authz_test.go
backend/scoreserver/admin/auth/model.conf
backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/server.go
backend/scoreserver/admin/server_test.go
backend/scoreserver/admin/team.go
backend/scoreserver/admin/team_test.go
backend/scoreserver/config/config.go
backend/scoreserver/scoreserver.go

closes #899 
#1036 で導入した Viewer の情報を基に [casbin](https://casbin.org/) のポリシーを適用する

feat: Admin API authorization

---

backend/scoreserver/admin/team_test.go
backend/scoreserver/domain/team.go

ゼロ値が通るとまずく、2ケタに収まらないコードもまたエッジケースである

fix: deny team code 0 and 100

---

backend/.golangci.yaml
backend/pkg/pgxutil/open.go
backend/schema.sql
backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/invitation.go
backend/scoreserver/admin/invitation_test.go
backend/scoreserver/admin/server.go
backend/scoreserver/domain/clock.go
backend/scoreserver/domain/error.go
backend/scoreserver/domain/invitation.go
backend/scoreserver/domain/invitation_test.go
backend/scoreserver/domain/team.go
backend/scoreserver/domain/team_test.go
backend/scoreserver/infra/pg/invitation_code.go
backend/scoreserver/infra/pg/invitation_code_test.go
backend/scoreserver/infra/pg/repository_test.go

feat: implement admin.v1.InvitationService

---

backend/pkg/pgtest/pgtest.go
backend/scoreserver/admin/invitation_test.go
backend/scoreserver/admin/server_test.go
backend/scoreserver/admin/team_test.go
backend/scoreserver/infra/pg/invitation_code_test.go
backend/scoreserver/infra/pg/repository_test.go

Refactor pgtest

---

backend/scoreserver/admin/invitation.go
backend/scoreserver/admin/team.go
backend/scoreserver/domain/clock.go
backend/scoreserver/domain/invitation.go
backend/scoreserver/domain/invitation_test.go
backend/scoreserver/domain/team.go
backend/scoreserver/domain/tx.go
backend/scoreserver/infra/pg/repository.go

ワークフローという名前の構造体を使うのではなくて単純な関数 + 外部依存という形にした

refactor: domain workflow

---

backend/schema.sql
backend/scoreserver/domain/fixture.go
backend/scoreserver/domain/invitation_test.go
backend/scoreserver/domain/team_member.go
backend/scoreserver/domain/team_member_test.go
backend/scoreserver/infra/pg/team_member.go
backend/scoreserver/infra/pg/team_member_test.go
backend/seed.sql

チームメンバーとしてのユーザーと，ユーザーのチームへの招待を実装した

feat: team member

---

backend/compose.yaml

feat: remove adminer service from compose file

---

backend/scoreserver/domain/user.go
backend/scoreserver/infra/pg/user.go
backend/scoreserver/infra/pg/user_test.go

feat: add user profile access

---

backend/scoreserver/contestant/server.go
backend/scoreserver/contestant/viewer.go
backend/scoreserver/domain/team_member.go

contestant.v1.ViewerService を実装した

feat(api): implement contestant.v1.ViewerService

---

backend/.golangci.yaml
backend/pkg/pgtest/pgtest.go
backend/pkg/redistest/redis.go
backend/pkg/redistest/redis_test.go
backend/scoreserver/admin/auth/authn_test.go
backend/scoreserver/admin/invitation_test.go
backend/scoreserver/admin/team_test.go
backend/scoreserver/contestant/session/session_test.go
backend/scoreserver/domain/invitation_test.go
backend/scoreserver/domain/team_member_test.go
backend/scoreserver/domain/user_test.go
backend/scoreserver/infra/pg/invitation_code_test.go
backend/scoreserver/infra/pg/team_member_test.go
backend/scoreserver/infra/pg/user_test.go

Go 1.24 から [(*testing.T).Context](https://pkg.go.dev/testing#T.Context) が使えるようになったので切り替える

test: use t.Context

---

backend/scoreserver/infra/pg/invitation_code.go
backend/scoreserver/infra/pg/invitation_code_test.go
backend/scoreserver/infra/pg/team_member.go
backend/scoreserver/infra/pg/team_member_test.go

チームに最大メンバー数を入れていたのにクエリに反映するのを忘れていた……

fix(team): add max_members field to team queries

---

backend/scoreserver/domain/invitation.go
backend/scoreserver/infra/pg/invitation_code.go
backend/scoreserver/infra/pg/invitation_code_test.go

feat: implement invitation code access

---

backend/compose.yaml
backend/scripts/local-exec

jaeger の port forward が不安定なので OpenTelemetry Collector を挟むようにした

refactor: add otelcol for local dev

---

README.md
backend/README.md
frontend/README.md

docs: ドキュメントを最新に

---

backend/.golangci.yaml
backend/schema.sql
backend/scoreserver/domain/problem.go
backend/scoreserver/domain/problem_test.go
backend/scoreserver/infra/pg/column.go
backend/scoreserver/infra/pg/problem.go
backend/scoreserver/infra/pg/problem_test.go
backend/seed.sql

問題に関するドメインモデルを定義した
closes: #1306

feat: problem domain

---

backend/cmd/scoreserver/config.go

feat(cmd/scoreserver): more config errors

---

backend/README.md
backend/cmd/scoreserver/config.go
backend/go.mod
backend/go.sum
backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/problem.go
backend/scoreserver/admin/server.go
backend/scoreserver/config/config.go
backend/scoreserver/domain/problem.go
backend/scoreserver/infra/growi/client.go
backend/scoreserver/infra/growi/page.go
backend/scoreserver/infra/pg/problem.go
backend/scoreserver/infra/pg/problem_test.go

implement admin.v1.ProblemService

---

frontend/packages/contestant/app/features/problem/index.ts
frontend/packages/contestant/app/routes.gen.ts
frontend/packages/contestant/app/routes/~__root.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.tsx
frontend/packages/contestant/app/routes/~problems.index/page.stories.tsx
frontend/packages/contestant/app/routes/~problems.index/page.tsx
frontend/packages/contestant/app/routes/~problems.index/problem-item.stories.tsx
frontend/packages/contestant/app/routes/~problems.index/problem-item.tsx
frontend/packages/contestant/app/routes/~problems.index/~route.tsx
frontend/packages/contestant/tailwind.config.js

問題一覧閲覧画面を実装

---

backend/scoreserver/contestant/problem.go
backend/scoreserver/contestant/server.go

contestant.v1.ProblemService の問題マスタに関する部分を実装

---

frontend/packages/contestant/app/components/app-shell/layout.tsx
frontend/packages/contestant/app/components/app-shell/navbar.tsx
frontend/packages/contestant/app/index.tsx
frontend/packages/contestant/app/routes/~__root.tsx
frontend/packages/contestant/app/routes/~problems.index/page.tsx
frontend/packages/contestant/app/routes/~problems.index/problem-item.tsx
frontend/packages/contestant/package.json
frontend/pnpm-lock.yaml

- レイアウトが壊れていたのを直した
- 認証エラーが起きると画面が壊れていたのを直した
- ナビゲーションバーが反応していなかったのを直した

fix contestant /problems page

---

backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/contestant.go
backend/scoreserver/admin/server.go
backend/scoreserver/connectdomain/interceptor.go
backend/scoreserver/contestant/auth_signup_test.go
backend/scoreserver/contestant/profile.go
backend/scoreserver/contestant/server.go
backend/scoreserver/domain/discord.go
backend/scoreserver/domain/team_member.go
backend/scoreserver/domain/user.go
backend/scoreserver/domain/user_test.go
backend/scoreserver/infra/pg/column.go
backend/scoreserver/infra/pg/invitation_code.go
backend/scoreserver/infra/pg/problem.go
backend/scoreserver/infra/pg/team.go
backend/scoreserver/infra/pg/user.go
backend/scoreserver/infra/pg/user_test.go

チームメンバーの取得関連の API を実装した
ダッシュボードのチーム一覧画面は実装していない

チームメンバーを一覧できるようにした

---

backend/compose.yaml
backend/schema.sql
backend/scripts/migrate
backend/view.sql

feat: define DB schema

---

backend/schema.sql
backend/scoreserver/domain/answer.go
backend/scoreserver/domain/answer_test.go
backend/scoreserver/domain/fixture.go
backend/scoreserver/infra/pg/answer.go
backend/scoreserver/infra/pg/answer_test.go
backend/scoreserver/infra/pg/otel.go
backend/seed.sql

- **feat(answer): add answer domain**
- **feat(answer): implement data store**

answer domain

---

backend/scoreserver/contestant/answer.go
backend/scoreserver/contestant/server.go
backend/scoreserver/domain/answer.go
backend/scoreserver/infra/pg/answer.go
backend/scoreserver/infra/pg/answer_test.go
backend/scoreserver/infra/pg/problem.go

https://github.com/ictsc/ictsc-regalia/issues/1301

feat: implement contestant.v1.AnswerService

---

backend/.editorconfig
backend/schema.sql
backend/seed.sql

https://github.com/ictsc/ictsc-regalia/issues/1413 phase1

feat(answer): add created_at_range

---

backend/schema.sql
backend/scoreserver/infra/pg/answer.go
backend/scoreserver/infra/pg/answer_test.go
backend/seed.sql

chore: replace to answers.created_at_range

---

backend/scoreserver/contestant/answer.go
backend/scoreserver/domain/answer.go

https://github.com/ictsc/ictsc-regalia/pull/1431 で定義したメタデータを実装した

feat(answer): implement answer metadata api

---

frontend/packages/contestant/app/components/score.tsx
frontend/packages/contestant/app/features/answer.ts
frontend/packages/contestant/app/routes/~problems.$code/page.stories.tsx
frontend/packages/contestant/app/routes/~problems.$code/page.tsx
frontend/packages/contestant/app/routes/~problems.$code/submission-form.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.lazy.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.tsx
frontend/packages/contestant/app/routes/~problems.index/page.tsx
frontend/packages/contestant/app/routes/~problems.index/problem-item.stories.tsx
frontend/packages/contestant/app/routes/~problems.index/problem-item.tsx

closes #1301
競技者が回答を提出できるようにした

feat: contestant answer submission

---

backend/schema.sql
backend/scoreserver/domain/answer.go
backend/scoreserver/infra/pg/answer_test.go
backend/seed.sql
frontend/packages/contestant/app/routes/~problems.$code/page.tsx
frontend/packages/contestant/app/routes/~problems.$code/submission-form.tsx

fix: 回答→解答

---

backend/pkg/pgtest/pgtest.go
backend/schema.sql
backend/scoreserver/domain/mark.go
backend/scoreserver/infra/pg/answer.go
backend/scoreserver/infra/pg/column.go
backend/scoreserver/infra/pg/mark.go
backend/scoreserver/infra/pg/mark_test.go
backend/seed.sql
backend/view.sql

- **feat(mark): add mark domain**
- **fix: apply view**
- **feat(mark): add datastore implementation**

feat: mark domain

---

frontend/packages/contestant/app/routes/~problems.$code/submission-form.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.lazy.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.tsx

feat(problem): Added time control for submit answer button

---

backend/pkg/pgtest/pgtest.go
backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/mark.go

feat(mark): add admin.v1.MarkService/{ListMarkingResults,CreateMarkingResult}

---

frontend/packages/admin/app/index.tsx
frontend/packages/admin/app/routes/~submissions.$problem.$team.$id/~route.tsx
frontend/packages/admin/package.json
frontend/pnpm-lock.yaml

feat: 採点フォームを実装

---

backend/schema.sql
backend/scoreserver/infra/pg/__snapshots__/TestGetAnswerDetail/ok.snap.json
backend/scoreserver/infra/pg/__snapshots__/TestGetLatestAnswersByTeamProblem/exists.snap.json
backend/scoreserver/infra/pg/__snapshots__/TestListAnswers.snap.json
backend/scoreserver/infra/pg/__snapshots__/TestListAnswersByTeamProblem/ok.snap.json
backend/scoreserver/infra/pg/__snapshots__/TestListMarkingResults.snap.json
backend/scoreserver/infra/pg/answer.go
backend/view.sql

fix: category schema

---

backend/scoreserver/admin/mark.go
backend/scoreserver/domain/mark.go

feat(answer): add scores to admin.v1.Answer

---

backend/scoreserver/domain/mark.go
frontend/packages/admin/app/routes/~submissions.index/~route.tsx

feat: add mark score to admin console

---

.github/workflows/wf-docker-build.yaml
backend/Dockerfile
docker-bake.hcl

scoreserver という名称は frontend も含みそうでおかしい

chore: create ghcr.io/ictsc/ictsc-regalia/backend

---

backend/view.sql

feat: add view for calcurate scores

---

frontend/packages/contestant/app/components/app-shell/account-menu.tsx
frontend/packages/contestant/app/routes/~problems.$code/page.tsx

remove unimplemented feature

---

backend/cmd/scoreserver/config.go
backend/cmd/scoreserver/option.go
backend/scoreserver/admin/schedule.go
backend/scoreserver/admin/server.go
backend/scoreserver/config/config.go
backend/scoreserver/contestant/contest.go
backend/scoreserver/contestant/server.go
backend/scoreserver/domain/schedule.go
backend/scoreserver/domain/schedule_phase.go
backend/scoreserver/infra/fake/schedule.go
backend/scoreserver/scoreserver.go

- **feat(schedule): implement domain**
- **feat(schedule): implement contestant.v1.ContestService/GetSchedule**
- **fix(schedule): handle unbound schedule entries**
- **feat(schedule): implement marshalers to phase**
- **feat(schedule): implement fake schedule for test**
- **feat(schedule): use fake schedule**

競技者側スケジュール

---

backend/scoreserver/connectdomain/interceptor.go
backend/scoreserver/contestant/answer.go
backend/scoreserver/contestant/notice.go
backend/scoreserver/contestant/problem.go
backend/scoreserver/contestant/schedule.go
backend/scoreserver/contestant/server.go

feat: enforce schedule rules

---

frontend/packages/contestant/app/routes.gen.ts
frontend/packages/contestant/app/routes/~announces.$slug/~route.lazy.tsx
frontend/packages/contestant/app/routes/~announces.$slug/~route.tsx
frontend/packages/contestant/app/routes/~announces.index/page.tsx
frontend/packages/contestant/app/routes/~announces.index/~route.tsx
frontend/packages/contestant/app/routes/~announces.tsx

feat(announce): render announces

---

backend/schema.sql
backend/scoreserver/domain/deployment.go
backend/scoreserver/domain/deployment_status.go
backend/scoreserver/infra/pg/__snapshots__/TestListDeployments.snap.json
backend/scoreserver/infra/pg/deployment.go
backend/scoreserver/infra/pg/deployment_test.go
backend/seed.sql

deployment domain

---

backend/scoreserver/admin/auth/policy.csv
backend/scoreserver/admin/deployment.go
backend/scoreserver/admin/server.go

feat(deploy): implement admin.v1.DeploymentService/ListDeployments

---

frontend/packages/contestant/app/routes/~problems.$code/~route.lazy.tsx

空のときにバグる
optional chain の挙動が知ってるものと違う気がするんですが……

fix: redeploy when empty

---

backend/scoreserver/domain/deployment.go

fix(deploy): fix first redeployment

---

backend/cmd/batch/config.go

fix(batch): fix token reusing logic

---

backend/scoreserver/infra/pg/answer.go

Fix tracer typo for `ListAnswersByTeamProblemForPublic`

---

backend/schema.sql
backend/scoreserver/infra/pg/problem_test.go

feat: restrict answer deletion

---

frontend/packages/admin/app/routes/~submissions.$problem.$team.$id/~route.tsx

fix: max score handling

---

backend/scoreserver/domain/deployment.go
backend/scoreserver/domain/mark.go

fix: deployment count is not finished

---

frontend/packages/contestant/app/components/app-shell/header.tsx
frontend/packages/contestant/app/components/app-shell/layout.tsx
frontend/packages/contestant/app/routes/~index/page.tsx
frontend/packages/contestant/app/routes/~signin/page.tsx

iOS Safari だと position: fixed の振舞いが他のブラウザと違っている
その他モバイルから見たときのスタイルを軽く修正した

fix header

---

frontend/packages/contestant/app/routes/~problems.$code/deployments.tsx
frontend/packages/contestant/app/routes/~problems.$code/~route.lazy.tsx

feat: show allowed deployment count for empty view

---

frontend/packages/contestant/app/routes/~problems.$code/submission-form.tsx

ダイアログを Suspense Boundary にすると直る

fix: glitch on confirm answer submission

---

backend/go.mod
backend/tools/go.mod

go.mod の toolchain directive を設定した

chore: set toolchain
