frontend/octavio/__test__/pages/index.test.tsx, frontend/octavio/__test__/pages/login.test.tsx, frontend/octavio/__test__/pages/notices.test.tsx, frontend/octavio/__test__/pages/problems/[problemId].test.tsx, frontend/octavio/__test__/pages/problems/index.test.tsx, frontend/octavio/__test__/pages/profile.test.tsx, frontend/octavio/__test__/pages/ranking.test.tsx, frontend/octavio/__test__/pages/scoring/[code].test.tsx, frontend/octavio/__test__/pages/scoring/index.test.tsx, frontend/octavio/__test__/pages/signUp.test.tsx, frontend/octavio/__test__/pages/team_info.test.tsx, frontend/octavio/__test__/pages/users.test.tsx, frontend/octavio/components/MarkdownPreview.tsx, frontend/octavio/components/NotificationCard.tsx, frontend/octavio/pages/problems/[problemId].tsx, frontend/octavio/pages/scoring/[code].tsx, frontend/octavio/pages/scoring/index.tsx
* refactor: common-layout, base-layout をモックするように変更
* refactor: MarkdownPreview の content にデフォルト引数を追加
=> refactor: common-layout, base-layout をモックするように変更

.github/dependabot.yml
=> use 'npm' for yaml value

backend/pkg/db/redis/operations.go, backend/pkg/db/redis/redis.go
少ないDB数でユニークキーを生成するため、自由なスキーマでデータを入れられる利点を生かし、キーの前にサービス名を付けることで唯一性を担保するようになった
これで、極論すべてのサービスで同じDBを使うことも可能
=> Redis Clientにサービス名を登録するように

init.sh
`init.sh` で task コマンドが呼び出せないときに表示されるインストール用ページのリンクが切れているため、修正します。
=> Fix broken link in `init.sh`

.github/renovate.json
テストももう走っていないので更新され続けると壊れると思われる
=> 退避した旧フロントエンド実装の deps を更新しない

backend/buf.gen.yaml, backend/tools.go
protoc のバージョンがサイレントに変わって CI が落ちるなどの問題がある。
buf remote plugin のバージョンを指定するという方法もあるが，Renovate で直接は管理できない(Custom Manager が必要)なのであまりやりたくない。
他のツールと同様に tools.go の管理下に置くことにする
=> chore: manage protoc as go tools

backend/cmd/scoreserver/config.go, backend/cmd/scoreserver/option.go, backend/go.mod, backend/go.sum, backend/scoreserver/config/config.go, backend/scoreserver/contestant/auth.go, backend/scoreserver/contestant/server.go, backend/scoreserver/contestant/session/session.go, backend/scoreserver/domain/error.go, backend/scoreserver/domain/user.go, backend/scoreserver/infra/discord/client.go, backend/scoreserver/infra/discord/identity.go, backend/scoreserver/scoreserver.go
closes #52
Discord OAuth2 を使ったログインを実装した
既にユーザーが登録されているならログインしてユーザーセッションを設定し，未登録であるならば OAuth2 で得た Discord のユーザー情報を持った登録用セッションを設定する
=> feat: implement discord auth

backend/scoreserver/contestant/auth.go
BaseURL.Pathが空の場合、クッキーの正しい処理を確実にするためにクッキーのパスを"/"に設定します。
これにより、パスが空の場合にクッキーが正しく設定されない問題が修正されます。
=> fix: handle empty cookie path as root path

backend/Dockerfile, backend/buf.gen.yaml, backend/generate.go, backend/go.mod, backend/scripts/migrate, backend/tools.go
Go 1.24 から導入された go.mod の tool directive を使ってツール類を管理するようにする
手元の Go のバージョンが古くても go tool コマンドは既に存在することと，ツールチェインの自動ダウンロード機能によって使うことができる(Go 1.23.6 で確認した)
=> chore: use go tools

backend/pkg/ratelimiter/redis.go, backend/pkg/ratelimiter/redis_test.go, backend/scoreserver/contestant/auth.go, backend/scoreserver/contestant/auth_signup.go, backend/scoreserver/contestant/auth_signup_test.go, backend/scoreserver/contestant/server.go, backend/scoreserver/contestant/session/session.go, backend/scoreserver/domain/discord.go, backend/scoreserver/domain/error.go, backend/scoreserver/domain/invitation.go, backend/scoreserver/domain/invitation_test.go, backend/scoreserver/domain/team_member.go, backend/scoreserver/domain/team_member_test.go, backend/scoreserver/domain/tx.go, backend/scoreserver/domain/user.go, backend/scoreserver/domain/user_test.go, backend/scoreserver/infra/pg/invitation_code.go, backend/scoreserver/infra/pg/invitation_code_test.go, backend/scoreserver/infra/pg/user.go, backend/scoreserver/infra/pg/user_test.go
競技者向け API にユーザー登録のためのエンドポイント(`/auth/signup`)を追加した
Cookie を制御するため，Connect API ではなく JSON API として作っている
また，ユーザー登録フォームから扱われることが想定されるため，できるだけ多くのエラーを返すようにしている
=> feat: contestant signup

backend/cmd/scoreserver/config.go, backend/pkg/httputil/csrf.go, backend/scoreserver/config/config.go, backend/scoreserver/contestant/server.go
CSRF 攻撃の対策として，Origin と Sec-Fetch-Site をチェックするミドルウェアを追加した。
既に認証用の Cookie は SameSite: Strict なものしかないのでそれで十分かもしれないが……
FYI: https://blog.jxck.io/entries/2024-04-26/csrf.html
=> feat: csrf protection

backend/scoreserver/contestant/auth_signup.go
/auth/signup の`Content-Type`ヘッダが`application/json`になっていないことに気付いたので設定
`(net/http.ResponseWriter).WriteHeader`の後はヘッダを変えても効果がないことを失念していた……
=> fix: /auth/signup の Content-Type を正しく設定する

frontend/packages/contestant/app/features/viewer/signup.ts, frontend/packages/contestant/app/routes/~signup/~route.tsx
/signup で登録した後に / に遷移しないことがあった．
登録フォームの完了後に`router.invalidate`を呼んでリロードし，その結果をもとに遷移するようにした．
より通常のフォームに近い実装ではあるが，若干ピタゴラスイッチ的ではある……
=> fix: 登録完了時にページ遷移しないことがあったのを修正

frontend/packages/contestant/app/routes/~signin/page.tsx
ロゴの URL は Vite から来たものを使う。
たまたまローカルだと動いていたがおそらくプロダクションだとパスが違って見えなかったはず
=> Discord のロゴが Storybook で壊れていたのを修正

.github/actions/setup-go/action.yaml
Go Module Cache が太り続けていそうなのである閾値を超えたら全部消してしまうことにする
閾値は適当に調整する
=> chore(ci): clean large module cache

backend/scoreserver/domain/team_problem.go
=> チームから見える問題に関するドメインを追加

.github/actions/setup-go/action.yaml
しばらく動かしてみたら 246MB くらいあったので閾値を余裕を持って 300MB くらいにしておく
=> CI で go clean -modcache が走る閾値を大きくした

frontend/packages/contestant/app/components/app-shell/index.ts, frontend/packages/contestant/app/components/app-shell/layout.tsx, frontend/packages/contestant/app/routes/~problems.$code/page.tsx
左側のナビゲーションバーを開閉する際にレイアウトが変化するトランジションが発生する．
内容が grid や flex による現在のボックスサイズを参照する制御になっている場合は正しくトランジションが行われるが，
問題詳細ページは width によって手動で制御されているためトランジションされずにレイアウトが崩れていた．
トランジションの状態を Context により伝達し，width で大きさを制御しているコンポーネントに開閉中のみ width をトランジションさせるように伝えることで正しいレイアウトが反映されるようにした．
=> fix: navbar transitioning on /problems/$code

frontend/packages/config/eslint/config.js, frontend/packages/contestant/app/components/markdown/markdown.module.css, frontend/packages/contestant/app/components/markdown/markdown.tsx
コード系の表示をサポートした(ブロックコードのシンタックスハイライトは未対応)．引用表示もサポートした．
数式が表示されない場合に KaTeX のスタイルが読まれないようにした(KaTeX 自体は依然としてロードされる)
=> feat: Markdown の表示を改善

backend/schema.sql
本当はこれらの拡張が既に入っているイメージを開発用に使うべきかもしれない
=> fix: remove extensions not included in postgres image

frontend/packages/contestant/app/components/app-shell/layout.tsx
grid layout を使って App Shell のレイアウトを制御していたが，overflow 周りの挙動が難しいので全て fixed で配置して位置計算するようにした
=> fix: use fixed instead of grid for app-shell layout

backend/scoreserver/contestant/problem.go, backend/scoreserver/domain/problem.go, backend/scoreserver/domain/team_problem.go, frontend/packages/contestant/app/features/problem/index.ts
再展開可能か?という状態である`Redeployable`を定義し，競技者 API から参照できるようにした
=> feat(problem): add redeployable state

.github/workflows/backend-ci.yml, backend/schema.sql
view から参照されるので schema test が落ちるのは想定内です
```console
echo "DROP VIEW latest_marking_results;" | psql
migrate
```
=> chore!(marking): make marking_results.created_at TIMESTAMPTZ

backend/pkg/connectutil/otel_interceptor.go
=> feat: trust remote OTel traceparent

frontend/packages/admin/app/routes/~submissions.$problem.$team.$id/~route.tsx
提出された解答を Markdown レンダラを介さずに単に pre タグで囲んだものが閲覧できるようにします。
=> feat: Add a spoiler for showing answers without rendering them as Markdown documents

.github/renovate.json
PR が多すぎると Actions のキューが詰まって進行しなくなるので
=> chore(renovate): limit concurrent PRs
